### ISSUE TITLE
Multiple Mediators

### ISSUE THREAD

**Issue by athammad** [nhejazi/medshift#29]
Hi Nima, 

First of all, thank you for your amazing work! 
I am trying to decompose the effect of multiple mediators ideally using `xgboost`. On the documentation, I see that `medshift` should be able to work with multiple mediators but I keep getting the estimation of only one mediator, even using the default example.

Best wishes, 
Ahmed

```

library(medshift)
library(data.table)

make_simple_mediation_data <- function(n_obs = 1000) {
  W <- rbinom(n_obs, 1, prob = 0.50) 
  A <- as.numeric(rbinom(n_obs, 1, prob = W / 4 + 0.1))
  z1_prob <- 1 - plogis((A^2 + W) / (A + W^3 + 0.5))
  Z <- rbinom(n_obs, 1, prob = z1_prob)
  Y <- Z + A - 0.1 * W + rnorm(n_obs, mean = 0, sd = 0.25)
  
  data <- as.data.table(cbind(Y, Z, A, W))
  setnames(data, c("Y", "Z", "A", "W"))
  return(data)
}
set.seed(75681)
example_data <- make_simple_mediation_data()
example_data$ZZ<-sample(c(0,1),dim(example_data)[1],replace = TRUE)

os_medshift <- medshift(W = example_data$W, A = example_data$A,
                        Z = cbind(example_data$Z,example_data$ZZ), Y = example_data$Y,
                        delta = 3, 
                        g_learners =sl3::Lrnr_xgboost$new() ,
                        e_learners =sl3::Lrnr_xgboost$new() ,
                        m_learners =sl3::Lrnr_xgboost$new() ,
                        phi_learners =sl3::Lrnr_xgboost$new() ,
                        estimator = "onestep",
                        estimator_args = list(cv_folds = 3))
summary(os_medshift)


```

**Comment by nhejazi** [comment]
@athammad, thanks for your question. Unfortunately, the effect you appear to describe does not align with the target parameter(s) whose estimators we implement in this package. Note that the effects we describe in https://arxiv.org/abs/1901.02776 are stochastic direct and indirect effects that are based on a _joint_ stochastic intervention that generates counterfactuals based on modifying the exposure but drawing the mediator(s) based on the (true) _natural_ distribution of the exposure.

In order to accommodate multiple mediators, we include a re-parameterization that substitutes a mediation mechanism (e.g., f(Z | A, W)) for an exposure mechanism conditional on the mediators (e.g., f(A | Z, W)), thereby allowing for multiple mediators to be easily considered while avoiding the complications that would arise from estimating a joint conditional distribution over multiple mediators. Thus, the effects you have estimated in your example correspond to the direct and indirect effects for multiplying the odds of exposure by 3 while drawing the mediators (Z and ZZ) from the natural distribution of the exposure (prior to multiplying it's odds by 3). The effect decomposition we provide does not partition the effects through individual mediators, as that would be a different causal inference problem entirely.
